### ISSUE TITLE
Restricting Value to 0..0 crashes CLI [Medium-Low Priority]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#35]
Not sure I'm reporting this against the right module, but here goes:
In shr_observation, the Observation.Value is 0..1.  Panel is based on Observation.  I want to constrain the Value in panel to 0..0.  If I try:

EntryElement:	Panel
Based on:		Observation
0..0			Value   // BAD!!

Then I get the following error 
 ERROR shr: Failed to resolve definition for Value. (module=shr-text-input)
   file: C:\Users\mkramer\Documents\GitHub\shr_spec\spec\shr_observation.txt

Shortly thereafter, the same declaration causes CLI to crash:

if (typeof element.value !== 'undefined') {
                    ^
TypeError: Cannot read property 'value' of undefined
    at Object.valueAndFields (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\common.js:94:21)
    at FHIRExporter.buildUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\export.js:237:32)
    at FHIRExporter.addFieldToUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\export.js:253:45)
    at FHIRExporter.buildUnmappedPathsTree (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\export.js:238:12)
    at FHIRExporter.mappingToProfile (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\export.js:158:56)
    at FHIRExporter.export (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\export.js:64:12)
    at Object.exportToFHIR (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\node_modules\shr-fhir-export\lib\export.js:27:25)
    at Object.<anonymous> (C:\Users\mkramer\Documents\GitHub\shr-cli-5.0.0-beta.4\app.js:70:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by cmoesel** [comment]
The current tooling doesn't allow the _Value_ cardinality to be changed in this way -- although it could be considered for future versions.  This will, of course, depend on if we keep the notion of _Value_ at all.

For the time being, you can add the following rule in your fhir mapping to at least constrain it out of the FHIR profiles:
```
Panel:
	constrain value[x] to 0..0
```

When I tried this, however, I got 4 errors because there are 4 elements that are based on `Panel` but still declare a `Value` -- so it generates an error since it can't fit the value into `0..0`.

**Comment by cmoesel** [comment]
This was fixed in `shr-text-import` v5.2.0.
