### ISSUE TITLE
Cannot export elements with long FQN

### ISSUE THREAD

**Issue by Abhijay** [standardhealth/shr-fhir-export#45]
Building from the latest CIMI spec:

When the FQN of an element or extension exceeds ~64 characters, the FHIR-Exporter crashes. The only workaround right now is to reduce the length of the elements' names.

```

> Step 2: Building new IG
> FHIR Implementation Guide Publisher (3.0.1-11916) @ Friday, August 18, 2017 3:17:12 PM
> Detected Java version: 1.8.0_144 from /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre on x86_64 (64bit). 3641MB available
> Load Configuration from /Users/abhatnagar/Code/SHR/out/fhir/guide/shr.json       (00.0000sec)
> File log: /var/folders/1d/t7dd_tf55jvgz63lgk30dsvr0000gn/T/fhir-ig-publisher-tmp.log
> Root directory: /Users/abhatnagar/Code/SHR/out/fhir/guide                        (00.0058sec)
> Terminology Cache is at /Users/abhatnagar/Code/SHR/out/fhir/guide/txCache. 1 files in cache (00.0071sec)
> Load Validation Pack (internal)                                                  (00.0072sec)
> Definitions 3.0.1-11917                                                          (08.0786sec)
> Connect to Terminology Server at http://tx.fhir.org/r3                           (08.0788sec)
> Publishing Content Failed: Bad Resource Identity - should have the format [Type]/[id] where id is a valid FHIR id type:StructureDefinition/cimi-clinicaladverseeventreporting-AssociatedClinicalStudy-extension (09.0692sec)
>                                                                                  (09.0693sec)
> Use -? to get command line help                                                  (09.0694sec)
>                                                                                  (09.0695sec)
> Stack Dump (for debugging):                                                      (09.0696sec)
> java.lang.Exception: Bad Resource Identity - should have the format [Type]/[id] where id is a valid FHIR id type:StructureDefinition/cimi-clinicaladverseeventreporting-AssociatedClinicalStudy-extension
> 	at org.hl7.fhir.igtools.publisher.IGKnowledgeProvider.loadPaths(IGKnowledgeProvider.java:75)
> 	at org.hl7.fhir.igtools.publisher.IGKnowledgeProvider.<init>(IGKnowledgeProvider.java:53)
> 	at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:769)
> 	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:299)
> 	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:3589)
> 

```

**Comment by Abhijay** [comment]
This would be better to put in the cli branch.
