### ISSUE TITLE
Crash without Usable Diagnostic Information

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#58]
Version 5.2.  Fix, or at least give me a clue what I should be looking for and fixing in the CAMEO source:

C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\common.js:86
  const id = `${identifier.namespace.replace('.', '-')}-${identifier.name}`;
                          ^

TypeError: Cannot read property 'namespace' of undefined
    at fhirID (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\common.js:86:27)
    at Object.fhirURL (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\common.js:98:50)
    at FHIRExporter.getElementInExtension (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:1372:26)
    at FHIRExporter.getElementInExtension (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:1382:17)
    at FHIRExporter.applyConstraints (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:1320:32)
    at FHIRExporter.addExtension (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:1947:10)
    at FHIRExporter.addExtensions (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:1838:16)
    at FHIRExporter.mappingToProfile (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:176:12)
    at FHIRExporter.export (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:75:12)
    at Object.exportToFHIR (C:\Users\mkramer\Documents\GitHub\shr-cli-5.2.0\node_modules\shr-fhir-export\lib\export.js:33:25)

**Comment by cmoesel** [comment]
I've submitted a fix for code review.  In the mean-time, if you want to try it out download this file:
https://raw.githubusercontent.com/standardhealth/shr-fhir-export/ext_constraint_fixes_and_uscore_101/lib/export.js

And then copy it into your shr-cli folder at `node_modules/shr-fhir-export/lib/export.js`

**Comment by cmoesel** [comment]
Almost forgot:  You'll also need to uncomment the mappings for `CodeableConcept`, `Coding`, and `Quantity` in your SHR spec definitions.  Those are essential to the exporter working.

**Comment by cmoesel** [comment]
Fixed in `shr-fhir-export` v5.2.2.
